In [2]:
# importing libraries

import pandas as pd
from tqdm import tqdm, tqdm_pandas
tqdm.pandas(mininterval = 3)
import matplotlib.pyplot as plt
pd.options.mode.chained_assignment = None
import numpy as np

In [2]:
### analysis of the thirds dataset ###

# reading in the data
df = pd.read_csv(r"E:\Speechgraphs_paper\same_size_5_year_all_sciences_thirds\params_table.txt", sep = ",")

In [4]:
def clean_date(x):
    if x[0] == "_":
        return x[1:6]  
    elif x[5] == "_":
        return  x[0:5] 
    else:
        return x

In [5]:
df["Science"] = df.File.apply(lambda x: x[0:3])
df["Part"]  = df.File.apply(lambda x: x[4:5])
df["Valence"] = df.File.apply(lambda x: x[9:13])
df["Date"] = df.File.apply(lambda x: x[20:26])
df.Valence = df.Valence.apply(lambda x: "low" if x == "low_" else "high")
df.Date = df.Date.apply(lambda x: clean_date(x))
df["retracted"] = 0

In [ ]:
df.to_csv(r"E:\Speechgraphs_paper\same_size_5_year_all_sciences_thirds\final_table_non_retracted.csv", index = False)

In [3]:
### analysis of retracted dataset ###

# reading in the data

df_retracted = pd.read_csv(r"E:\Speechgraphs_paper\rejected_abstracts\same_size_5_year_all_sciences_thirds\params_table.txt", sep = ",")

In [ ]:
def clean_date(x):
    if x[0] == "_":
        return x[1:6]  
    elif x[5] == "_":
        return  x[0:5] 
    else:
        return x

In [ ]:
df_retracted["Science"] = df_retracted.File.apply(lambda x: x[0:3])
df_retracted["Part"]  = df_retracted.File.apply(lambda x: x[4:5])
df_retracted["Valence"] = df_retracted.File.apply(lambda x: x[9:13])
df_retracted.Valence = df_retracted.Valence.apply(lambda x: "low" if x == "low_" else "high")
df_retracted["retracted"] = 1

In [6]:
df_retracted.to_csv(r"E:\Speechgraphs_paper\rejected_abstracts\same_size_5_year_all_sciences_thirds\final_table_retracted", index = False)

In [3]:
### analysis of whole texts dataset ###
# reading in the data
df = pd.read_csv(r"E:\Speechgraphs_paper\same_size_5_year_all_sciences_whole_texts\params_table.txt", sep = ",")

In [4]:
def clean_date(x):
    if x[0] == "_":
        return x[1:6]  
    elif x[5] == "_":
        return  x[0:5] 
    else:
        return x

In [ ]:
df["Science"] = df.File.apply(lambda x: x[0:3])
df["Valence"] = df.File.apply(lambda x: x[8:9])
df["Date"] = df.File.apply(lambda x: x[20:26])
df.Valence = df.Valence.apply(lambda x: "low" if x == "low_" else "high")
df.Date = df.Date.apply(lambda x: clean_date(x))
df["retracted"] = 0

In [39]:
df_retracted

,File,WC,Nodes,Edges,RE,PE,L1,L2,L3,LCC,LSC,ATD,Density,Diameter,ASP,CC,Science,Part,Valence,retracted
0,bio_1_df_high_values_0,23,17,22,2,2,1,0,0,17,13,2.588235,0.139706,6,3.029412,0.000000,bio,1,high,1
1,bio_1_df_high_values_1,56,47,55,1,1,0,0,1,47,42,2.340425,0.049954,12,5.132285,0.028369,bio,1,high,1
2,bio_1_df_high_values_10,40,35,39,1,1,0,0,1,35,33,2.228571,0.063866,15,6.233613,0.016190,bio,1,high,1
3,bio_1_df_high_values_100,46,35,45,5,5,0,0,0,35,27,2.571429,0.067227,14,5.411765,0.021905,bio,1,high,1
4,bio_1_df_high_values_1000,60,53,59,0,0,0,0,0,53,46,2.226415,0.042816,17,6.777939,0.020800,bio,1,high,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19123,psy_3_df_low_values_5,47,30,46,7,8,0,1,1,30,21,3.066667,0.087356,13,4.947126,0.053175,psy,3,low,1
19124,psy_3_df_low_values_6,15,15,14,0,0,0,0,0,15,1,1.866667,0.133333,14,5.333333,0.000000,psy,3,low,1
19125,psy_3_df_low_values_7,21,17,20,2,2,0,0,1,17,11,2.352941,0.132353,10,4.022059,0.123529,psy,3,low,1
19126,psy_3_df_low_values_8,15,15,14,0,0,0,0,0,15,1,1.866667,0.133333,14,5.333333,0.000000,psy,3,low,1
19127,psy_3_df_low_values_9,22,22,21,0,0,0,0,0,22,1,1.909091,0.090909,21,7.666667,0.000000,psy,3,low,1

In [25]:
df.groupby("Date").mean(numeric_only=True)

,WC,Nodes,Edges,RE,PE,L1,L2,L3,LCC,LSC,ATD,Density,Diameter,ASP,CC,retracted
Date,,,,,,,,,,,,,,,,
00_05,35.153386,30.360053,34.153386,0.978730,1.161429,0.038095,0.183968,0.253598,30.360053,19.789577,2.207351,0.085066,14.973545,5.914240,0.017447,0.0
05_10,36.315926,31.311323,35.315926,1.050476,1.234392,0.037937,0.186349,0.257937,31.311323,20.671429,2.216666,0.081976,15.258360,6.014592,0.017112,0.0
10_15,37.945503,32.697513,36.945503,1.094074,1.287037,0.036402,0.194233,0.269048,32.697513,21.858413,2.224467,0.078195,15.636667,6.153988,0.017355,0.0
15_20,41.613122,35.575873,40.613122,1.265079,1.482963,0.036455,0.218677,0.303810,35.575873,24.629206,2.251630,0.071357,16.161429,6.343760,0.017969,0.0
80_85,27.003810,23.987619,26.003810,0.556508,0.692487,0.028730,0.136825,0.180794,23.987619,13.061323,2.117874,0.106178,13.998519,5.516045,0.015554,0.0
85_90,28.351005,24.998042,27.351005,0.650952,0.801746,0.029153,0.151640,0.199630,24.998042,14.235185,2.136310,0.103032,14.089312,5.561514,0.016003,0.0
90_95,30.637778,26.709788,29.637778,0.792804,0.954021,0.032698,0.161587,0.220106,26.709788,16.058519,2.165358,0.097373,14.331587,5.657579,0.016561,0.0
95_00,34.463122,29.570635,33.463122,1.034868,1.221058,0.035873,0.187725,0.265132,29.570635,19.223439,2.210380,0.088715,14.595026,5.768257,0.018365,0.0

In [26]:
df.groupby("Valence").mean(numeric_only=True)

,WC,Nodes,Edges,RE,PE,L1,L2,L3,LCC,LSC,ATD,Density,Diameter,ASP,CC,retracted
Valence,,,,,,,,,,,,,,,,
high,35.646640,30.713677,34.646640,1.022222,1.202037,0.034180,0.180767,0.253545,30.713677,20.165939,2.207674,0.085497,14.993862,5.916333,0.017003,0.0
low,32.224272,28.089034,31.224272,0.833651,1.006746,0.034656,0.174484,0.233968,28.089034,17.215833,2.174835,0.092476,14.767249,5.816161,0.017088,0.0

In [27]:
df.groupby("Science").mean(numeric_only=True)

,WC,Nodes,Edges,RE,PE,L1,L2,L3,LCC,LSC,ATD,Density,Diameter,ASP,CC,retracted
Science,,,,,,,,,,,,,,,,
bio,32.911435,28.875231,31.911435,0.782222,0.959028,0.029676,0.177593,0.210370,28.875231,17.717685,2.164124,0.090413,15.166343,5.960661,0.015341,0.0
che,37.347130,31.905787,36.347130,1.159352,1.373519,0.038380,0.216343,0.286481,31.905787,21.551111,2.239951,0.080937,15.106528,5.973200,0.019006,0.0
hum,31.466852,27.625787,30.466852,0.749028,0.890694,0.031250,0.142546,0.208287,27.625787,16.582963,2.141459,0.096425,14.740370,5.792627,0.014702,0.0
inf,33.510046,29.207593,32.510046,0.817361,0.996481,0.033657,0.180324,0.240093,29.207593,18.335370,2.181157,0.089344,14.939815,5.883162,0.016648,0.0
mat,34.442870,29.716852,33.442870,0.989352,1.164907,0.034907,0.176481,0.253843,29.716852,19.088333,2.205109,0.087032,14.882454,5.866143,0.017880,0.0
phy,35.387222,30.406991,34.387222,1.086065,1.272407,0.038796,0.187963,0.265463,30.406991,19.772037,2.214293,0.085257,15.048889,5.932561,0.017652,0.0
psy,32.482639,28.071250,31.482639,0.912176,1.073704,0.034259,0.162130,0.241759,28.071250,17.788704,2.192689,0.093498,14.279491,5.655373,0.018091,0.0

In [28]:
df.groupby("Part").mean(numeric_only=True)

,WC,Nodes,Edges,RE,PE,L1,L2,L3,LCC,LSC,ATD,Density,Diameter,ASP,CC,retracted
Part,,,,,,,,,,,,,,,,
1,33.603909,29.559841,32.603909,0.762321,0.919464,0.034226,0.158115,0.210139,29.559841,18.648353,2.157567,0.088474,15.113512,5.947831,0.014582,0.0
2,33.603909,28.778036,32.603909,1.016071,1.217877,0.039762,0.203095,0.284663,28.778036,18.357976,2.214842,0.091674,14.498730,5.732367,0.020006,0.0
3,34.598552,29.866190,33.598552,1.005417,1.175833,0.029266,0.171667,0.236468,29.866190,19.066329,2.201355,0.086811,15.029425,5.918542,0.016549,0.0